### ISSUE TITLE
Add the Copy

### ISSUE THREAD

**Issue by cswenor** [theWickedWebDev/ecp#1]
I'll send you the PDF again.

**Comment by theWickedWebDev** [comment]
![Image of Copy](https://drive.google.com/open?id=0B0oKGQRvJmRKVy1PaXVBdUg1eXhCcUJaZTMwZENXNEJvQkZF&authuser=0)

**Comment by theWickedWebDev** [comment]
![east coast product v4](https://cloud.githubusercontent.com/assets/7525324/6139176/acb19ed8-b156-11e4-945b-9dc660a96cc0.jpg)

**Comment by cswenor** [comment]
Obviously the footer needs to be styled up a bit.  the fonts look out of place.

**Comment by theWickedWebDev** [comment]
of course
